marks =[60.7,70.3,80.2,90.4,100.6]
print(len(marks))
print(marks[-3:-1])
marks.append(45.6)
marks.sort(reverse= True)
marks.count(90.4)
marks.remove(90.4)


print(marks)
#list practice questions
#question:- WAP to ask the user to enter theire name of theire favorite movie & Store them in a list 
# list=[]
# list.append(input("write 3 movies name:- "))
# print(list)
# print(type(list))
# #the above questionis solved 

#Question:- WAP to Check if a list containsa palindrome of element
# pal =["maam"]
# copy_list = pal.copy()

# if(copy_list == pal):
#     print("palindrome")
# else:
#     print("not Plaindrome")
